---
name: Linter

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read
  issues: write

jobs:
  lint:
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: false
	  LINTER_RULES_PATH: .github/workflows
          FILTER_REGEX_EXCLUDE: .*Assets/Input System/|Assets/TextMeshPro/|ProjectSettings/.*
