name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest
                             

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Super-Linter
      uses: super-linter/super-linter@v7.3.0
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISABLE_ERORS: true
        OUTPUT_DETAILS: detailed
        VALIDATE_ALL_CODEBASE: false
