name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  
                             

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Super-Linter
      uses: super-linter/super-linter@v7.3.0

